name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication
  pages: write     # Required for GitHub Pages deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages  # ✅ REQUIRED for deployment to GitHub Pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload files to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Adjust if your index.html is inside a subdirectory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
